main: me.LucasHeh.MobCoins.Main
author: LucasHeh
version: 1.0.0
name: MobCoins
depend: [Vault, IridiumSkyblock]
api-version: 1.16

commands:
  mobcoins:
    description: "Mobcoins"
    aliases: "mc"
  buy:
    description: "Sends player the servers donation link"
    aliases: ["purchase", "rank", "donate"]
  vp:
    description: "Vote party"
  el:
    description: "Enchantment List"
  warzone:
    description: "Teleport to warzone"
    aliases: ["pvp", "fight", "wz"]
  boss:
    description: "bosses"
    aliases: ["bosses", "bossegg"]
  blacksmith:
    description: "blacksmith"
  artisan:
    description: "artisan"
    aliases: ["customcraft", "cc"]
